### ISSUE TITLE
bug: code-folding works in lower split, but not upper

### ISSUE THREAD

**Issue by ssepan2** [PaulSquires/WinFBE#27]
RECREATE:
Create code; observe fold indicators when present. Split code window. Collapse a fold in lower pane. Observe that code is collapsed. In upper pane, choose any code (typically a different fold than what you collapsed in lower pane). Collapse code in upper pane.
ERROR:
Code in upper window does not collapse.
EXPECTED:
Code in upper window will collapse.
WORKAROUND:
none
VERSION:
2.1.8

**Comment by PaulSquires** [comment]
Message notifications were only checking for Window id IDC_SCINTILLA, however, multiple Scintilla windows can exist due to splitting. Implemented a new class method clsDocument.IsValidScintillaId to check for valid window id during notification messages. Clicking on fold margins now works correctly in either split window pane.
