### ISSUE TITLE
Compilers path in IDE X86 and X64

### ISSUE THREAD

**Issue by Spoiledpay** [PaulSquires/WinFBE#32]
Hello,
In the current version, the IDE uses two paths for x86 and x64. But in the newer freebasic compiler there is only one FBC.EXE compiler; Can we consider putting only FBC.EXE or do we have to put it in the x86 and x64 path for the build versions to be carried out? Or we will have a version that supports this adjustment.
thanks.

**Comment by PaulSquires** [comment]
The FreeBasic distributions (for Windows) ship separate x86 and x64 packages. I take those two distributions and combine them into one and that is the compiler package that I bundle with the WinFBE Studio download. Because both x86 and x64 co-exist in the same bundled package, it is necessary to name the FBC.EXE compiler files as FBC32.EXE and FBC64.EXE. As an aside, the next update to WinFBE will allow you to select the specific toolchain folder and it will be assumed that the compiler files will be named FBC32.EXE and FBC64.EXE. So you would just select the folder rather than having to specify the individual EXE names. This will allow you to have multiple toolchain versions that you could change amongst. Not many people would have a great need to change toolchains but some people like to use specific versions of the toolchains for speed or size purposes.
