### ISSUE TITLE
Problem with ListView

### ISSUE THREAD

**Issue by WillyAguilera1977** [PaulSquires/WinFBE#36]
I have a problem with the Listview. It doesn't display the string in the item correctly. It shows a 'w' (wello), instead of showing hello.
It also shows the headers without Visual Styles.
I show you an image of the program. What can be done?
How do I fix it.

![listview](https://user-images.githubusercontent.com/106629173/177430050-1645416b-f175-45b6-95fa-3c02459a4aa0.png)

Waiting for your answer, I greet you sincerely

**Comment by PaulSquires** [comment]
Hi, this type of technical support is best dealt with via the planetsquires support forum. Please register on the forum at https://www.planetsquires.com/protect/forum/index.php

I would need to see the code for your form and/or project. The visual styles are not showing because most likely you have not added a resource file to your form/project that references a valid manifest.xml file that enables visual themes. If you start your visual designer project by using WinFBE's "Project" functionality then the resource file and manifest file are added automatically. 

The text issue in your Listview is probably related to not using unicode strings.

Once again, this is better dealt with via the planetsquires support forum where you can post your code and get more complete answers.
