### ISSUE TITLE
Adding fbc to compiler setup

### ISSUE THREAD

**Issue by lonnietc** [PaulSquires/WinFBE#37]
Hello,

I installed WinFBE but it does not seem to have the fbc.exe listed in the toolchain in the "Environment Options" ---> "Compiler Setup" and does not seem to allow me to browse to add a location on my Windows 11 system.

Hoe can this be fixed?

**Comment by PaulSquires** [comment]
WinFBE Suite comes packaged with the most recent FB compiler and toolchain. You will find the compiler located in the "toolchains" subfolder of your WinFBE installation. You can have as many toolchains as you wish (each in its own subfolder) thereby allowing for many different versions of the FB compiler. You can switch between the various FB compilers / toolchains from within WinFBE.  WinFBE looks for "fbc32.exe" and "fbc64.exe" as the FB compiler executable names. If you are not using the default WinFBE Suite setup (ie maybe you just downloaded the editor only), then you will need to move your compiler setup to a subfolder off of the Toolchains folder. For example, \toolchains\freebasic109\  You will also have to ensure that the compiler exe filenames are fbc32.exe and fbc64.exe. Older versions of the FB compiler only used fbc.exe rather than the 32 and 64 naming. If that is the case for you then most likely you have an older compiler. You must put the compiler in the toolchains subfolders. You can not use WinFBE with compilers located elsewhere in the file system.
