### ISSUE TITLE
Problem report

### ISSUE THREAD

**Issue by MOODSKY2002** [PaulSquires/WinFBE#42]
Problem report

(1) Ver3.0.1 and later, create forms, add buttons, and change the button text to Chinese. Save it and open it again, and the Chinese in the source code may become garbled.

(2) After winfbe3. x. There is a problem with the shader. Maybe there are too many codes in Chinese or a BI? Sometimes the shader gets stuck and the response is very slow. After switching to another BI, it is normal, and then switch back to continue the card.

(3) Can I add a function switch box at the top or somewhere of winfbe? It's more convenient

**Comment by PaulSquires** [comment]
Thank you for the bug report and the email that you sent me with the screenshots. I will investigate further over the next few days once Christmas holidays wind down. I believe it may be related to UTF-8 to UTF-16 conversion. The form file (*.design) is a standard JSON file that is saved in UTF-8 format. When that file is read from disk, the data is stored in UTF-16 so that the various Windows controls used in WinFBE (like the Properties, etc) can display them in native Windows encoding. Maybe something is causing a problem with certain Chinese characters during this transition.

As a workaround until this issue is fixed, you can save your form code file as UTF-16 unicode (rather than ANSI) and set your various control properties via code rather than in the Property Explorer. For example, in your Form's LOAD event you could set the textbox Text property.  Form1.Text1.Text = "my text"

**Comment by PaulSquires** [comment]
I have fixed the import of the UTF-8 JSON Design file to convert to unicode that WinFBE uses in its Win32 api based Windows controls. My limited test with Chinese characters seem to be working correctly. Please download the following ZIP archive and extract the two EXE's from the ZIP file to overwrite your existing 32 bit and 64 bit versions of your WinFBE EXE.
https://www.planetsquires.com/files/winfbe_chinese_issue.zip

Please let me know if this fixes your issue.

**Comment by PaulSquires** [comment]
Thank you for all your help with fixing this bug (via private email). The fixes will be in version 3.0.7 that will be released soon. Also, thanks for the information that for non-English users that they should enable "Beta: Use Unicode UTF-8 for worldwide language support" option in their WINDOWS 10 or 11 operating system. Happy New Year!
