### ISSUE TITLE
Chinese character support

### ISSUE THREAD

**Issue by ox000008** [PaulSquires/WinFBE#43]
The editor can not support Chinese character.

**Comment by PaulSquires** [comment]
By default, new files are opened using "ANSI" mode. You will need to switch the file to either "UTF-8 (BOM)" or "UTF-16 (BOM". You do that by clicking on the area in the status bar (located in the bottom right of the editor) and then select the file format.

**Comment by ox000008** [comment]
Hi Paul,

Thank you very much for your help, but there are still some issue, when I 'Compile and Run' or 'Quick Run', the result is like below. Do you know why, and can I fix it.

Best wishes!

Quick run.




---- Replied Message ----
From Paul ***@***.***>Date 02/13/2023 19:23 To ***@***.***>Cc ***@***.***>***@***.***>Subject Re: [PaulSquires/WinFBE] Chinese character support (Issue #43)
By default, new files are opened using "ANSI" mode. You will need to switch the file to either "UTF-8 (BOM)" or "UTF-16 (BOM". You do that by clicking on the area in the status bar (located in the bottom right of the editor) and then select the file format.

**Comment by PaulSquires** [comment]
Hi, did you intend to post a screenshot or a log output? All I see in your message is the result is "Quick run."
Also, are you using version 3.0.8 and the WinFBE_Suite that includes the FB compiler?

**Comment by ox000008** [comment]
Yes, I usd version 3.08 and send the screenshot.
Can you see the attached this time?




---- Replied Message ----
| From | Paul ***@***.***> |
| Date | 02/14/2023 20:01 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [PaulSquires/WinFBE] Chinese character support (Issue #43) |

Hi, did you intend to post a screenshot or a log output? All I see in your message is the result is "Quick run."
Also, are you using version 3.0.8 and the WinFBE_Suite that includes the FB compiler?

**Comment by ox000008** [comment]
OK, thanks. I will post it tomorrow morning.

Have a nice day!



---- Replied Message ----
| From | Paul ***@***.***> |
| Date | 02/14/2023 20:14 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [PaulSquires/WinFBE] Chinese character support (Issue #43) |

Sorry. I can not .
https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/attaching-files

Maybe you could post here a small snippet of your Chinese code and I will try to run it on my machine to see what error messages are generated.

**Comment by ox000008** [comment]
Here are the snapshots. Previously I have replied on the email, so the attached pictures was missing. 
Quick Run
![Quick Run](https://user-images.githubusercontent.com/35085005/218895957-aeae845d-1328-4fff-b707-96faafb5ba4c.png)

Compile and Run
![Compile and Run](https://user-images.githubusercontent.com/35085005/218896038-c8f4ead7-7682-4013-8404-d924ef955fec.png)

I have an idea that  Can WinFBE have the  function of "Open Declaration" like in the "Eclipse IDE"
![Open Declaration](https://user-images.githubusercontent.com/35085005/218897637-4b62ef6e-70eb-420e-bd18-4cd151e14017.png)

**Comment by PaulSquires** [comment]
Hi, thank you for the additional details. I have found an error in the "Quick Run" code that would cause display errors. Because I do not have a Chinese Windows version, I used the following source code to test:

I have also uploaded new EXE's for you to test. Simply replace your existing WinFBE EXE's with the ones in the zip archive.
[https://www.planetsquires.com/files/chinese_quickrun_test.zip](https://www.planetsquires.com/files/chinese_quickrun_test.zip
)
Please let me know if the problem is fixed.

#include "Afx/AfxWin.inc"

' Comment the following line to enable/disable the
' Chinese code page for console output. The Print 
' statement to the console window will look differently
' depending on whether the correct code page is set.
SetConsoleOutputCP(936)   

' Using WinFBX's dynamic CWSTR class
dim as CWSTR text1 
text1 = "吉伊杰杰勒 吉勒吾 诶艾伊 儿勒屁"
print text1

' Using FreeBasic's built in wstring
dim text2 as wstring * 256
text2 = "吉伊杰杰勒 吉勒吾 诶艾伊 儿勒屁"
print text2

' These calls to the Windows messagebox function should 
' correctly display the Chinese text regardless of what
' console code page is set.
AfxMsg( text1 )
AfxMsg( text2 )

**Comment by ox000008** [comment]
Hi Paul,

There is a new issue now. When I run the compiled "hello.exe", there is no output window display, but the process is running.
![image](https://user-images.githubusercontent.com/35085005/219230063-c03a7a15-b2ec-479c-bc0c-e8db3059eedf.png)

**Comment by PaulSquires** [comment]
From your screenshot it looks like you compiled the EXE for "Win64 GUI (Release)".
You should have compiled it for "Console" rather than "GUI".
Make the change and see if you continue to have a zombie process.

**Comment by ox000008** [comment]
yes, I make that mistake,
Now I run the hello.exe and the Chinese characters have overlaps.
![image](https://user-images.githubusercontent.com/35085005/219233534-13f90134-0def-49b6-a372-d8333060e8ed.png)

**Comment by ox000008** [comment]
And the Quick Run issue has been fixed.

**Comment by PaulSquires** [comment]
Hi, that is most likely due to the font that the console uses rather than anything related to WinFBE. Try changing to a different default font for your console and see if that fixes the display issue.

Thanks for reporting back that the Quick Run issue is fixed! That's great news.

**Comment by ox000008** [comment]
Hi Paul，

I did not find how to change the font or other configuration to fix the overlaps. Instead I can add a space between each character to avoid that issue. Thanks for help.
