### ISSUE TITLE
Not updating FUNCTION LIST

### ISSUE THREAD

**Issue by PikeBaySkywalker** [PaulSquires/WinFBE#48]
The function list is not updating properly.

**Comment by PaulSquires** [comment]
I need more information than this. Does the function list update after doing a SAVE of your code? A save triggers an update.

**Comment by PikeBaySkywalker** [comment]
It sometimes updates when saving, but never all of the functions.

**Comment by PaulSquires** [comment]
Can you post an example of the function of ones that do not show? Maybe I am not parsing the function signature correctly. 
I don't need the actual code within the function. Just the Function / End Function stuff.

**Comment by PikeBaySkywalker** [comment]
![20240319_105629](https://github.com/PaulSquires/WinFBE/assets/36343596/8462cf19-dedf-4c79-88dc-774f512a5053)

**Comment by PaulSquires** [comment]
Thanks. I will investigate today and see if I can re-create the issue. I will report back once I have more information. That is a simple Sub/End Sub so I am surprised that the parser is not picking it up.

**Comment by PaulSquires** [comment]
Would it be possible for you to email me that "Down the mine shaft.bas" file? I will analyze the parsing of it and then delete it. If you are okay with that then you can email it to support@planetsquires.com.  You may need to change the file extension to .TXT because sometimes email clients flag .BAS files as dangerous. If you prefer not to email it then I'll understand that as well.

**Comment by PaulSquires** [comment]
Thank-you for sending the file. The problem appears to be that the WinFBE parser is getting confused when the keyword "End" is used to end your program. It is thinking that it may be the start of an "End Sub" or "End Function" statement.

If you change line 90 in your program to use "Exit Do" rather than "End" then the function should then show in the Function List.

`      if wordsplit(1) = "q" or wordsplit(1) = "quit" or wordsplit(1) = "end" then exit do   'end 
`

BTW, I love the program you are writing. I grew up on those types of text adventures! 

I wish you a lot of success with your program and if you continue to have any trouble with WinFBE while writing it then please let me know.

**Comment by PikeBaySkywalker** [comment]
Thanks!

Den ons 20 mars 2024 12:41Paul Squires ***@***.***> skrev:
