### ISSUE TITLE
Default editor settings should be changed

### ISSUE THREAD

**Issue by Auios** [PaulSquires/WinFBE#9]
[WinFBE.ini](https://github.com/PaulSquires/WinFBE/blob/master/Settings/WinFBE.ini)
Some default settings should be changed:

`TabSize` should be 4. It's uncommon to see tab sizes at 3.

`HighlightCurrentLine` should be off by default. It's taboo for text editors to highlight the entire line

`ConfineCaret` should be enabled. It's more likely that the user just wants to set their caret to the end of the line rather than in the middle of the screen. Clicking in the middle of the screen is easier than maneuvering your cursor to where you want it. This way people can just eye-ball it.

`KeywordCase` should be set to 3 by default (original case) because the editor should not be meddling with the programmer's casing unless the programmer wants it. Typically they don't. Best to keep it off by default.

**Comment by weisborg** [comment]
I agree with the last two, but tab size of 4 is too wide and wastes space. If people can't tell indented text at 3 they need glasses. It shouldn't matter either since the IDE should only be storing Tabs and translating to the number of spaces, so one person's setting won't mess up another's format. The current line being worked on also needs indicated in some way. Often the scrollbar will even indicate position and changes for source control.

**Comment by Auios** [comment]
Highlighting the line on the scroll bar would be idea. Although highlighting the entire line in yellow is very obnoxious in my own opinion. I don't know of any other editors that even does this except this one. Not even VIM or that old QBasic IDE does this. Does it really _need_ to be indicated anyway? I don't think it _needs_ it. It's nice to have but not so nice when it's an obnoxious bright yellow line across your screen.

As for 3 vs 4 spaces tabs. I argue for 4 spaces because that's typically the norm. I can't imagine it getting out of hand and having indentations that span your entire screen. If you do have code that has indentations going across your screen then the programmer has bigger problems than 4 space indentations lol...

**Comment by mva1985** [comment]
I personally like to be able to set my own tab size AND  I like having the whole cursor line highlighted

but I'm just an amateur ;-)

**Comment by JoseRoca** [comment]
If Paul has chosen these default values it must be because there are the ones the he prefers. If you don't like them, just change them. Where is the problem?

**Comment by PaulSquires** [comment]
Thanks for your input regarding default ini values. All of those values can be changes by the user. I chose those settings because those are the ones that I use. Also, highlighting the current active edit line is a common feature in newer IDE's and I find it quite useful. The yellow line color can be changed (and actually the yellow does appear lighter/darker depending on your monitor as I have several computers and the deepness/lightness of the yellow seems to vary). I have always used 3 spaces for TABS as I find it lines up FOR/NEXT, IF/ENDIF blocks nicely. I have always dislikes confining caret to end of line as it makes my navigation from line to line more difficult (for me anyways). I always use Ctrl+Arrow keys (left/right/home/end) to navigate from word to word when on a line so the starting position is irrelevant for me.
